# Generated by Django 5.0.7 on 2024-08-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydjangoapp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Device', models.CharField(max_length=30)),
                ('Service', models.CharField(choices=[('1', 'Screen repair'), ('2', 'Battery replacement'), ('3', 'Chrging port repair'), ('4', 'Camera/sensor repairs'), ('5', 'Software troubleshooting'), ('6', 'Data recovery'), ('7', 'Other general repairs')], default='Pick the required service', max_length=30)),
                ('Message', models.TextField(default='Please describe the problem on your device')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(max_length=30),
        ),
    ]
